# yaml-language-server: $schema=./assets/schema/site.json

siteTitle:
  default: "deemoe's journal"
  ja: "deemoe のジャーナル"
  zh: "deemoe 的日志"

siteSubtitle:
  default: "Thanks for playing my game."
  zh: "眼见何事，情系何处，身在何方，心思何人"

siteDescription: "deemoe's journal"

siteKeywords: "static blog, markdown, github pages, blog"

avatar: assets/avatar.jpeg

resourceURL: "https://dee.moe/wwwroot/"

contentRoot: wwwroot

contentOutdatedDays: 180

cardCoverFallback: false

errorOverlay: true

pageSize: 8

defaultLanguage: en

themeMode: user

themePack: native

themeOverride: false

showAllPosts: true

landingTab: posts

repo:
  owner: deemoe404
  name: dee.moe
  branch: main

assetWarnings:
  largeImage:
    enabled: true
    thresholdKB: 500

reportIssueURL: "https://github.com/deemoe404/dee.moe/issues/new"
