# main menu navigation
menu:
  Home: /
  Gallery: /categories/Creation
  About: /about
  Archive: /archives

widgets:
  - tag
  - archive
  - recent_posts
  - category
  - profile

# social config
social:
  # zhihu:
  # twitter: /
  # facebook: /
  # linkedin:
  # instagram: /
  github: deemoe404
  # mastodon: '@meow@c7.io'

user:
  name: deemoe
  avatar: images/profile.jpg
  location: Earth
  description: 眼见何事，情系何处，身在何方，心思何人
  footnotes: # footnotes

# documents: https://github.com/utterance/utterances
# API config: https://utteranc.es/
comment_utteranc:
  enable: true
  repo: deemoe404/dee.moe # your blog repo


# documents: https://valine.js.org/quickstart.html
comment_valine:
  enable: false
  appId:
  appKey:

comment_disqus:
  enable: false
  url:  # the url of your website main domain like this https://xxx.xxx/
  name: # the short name in disqus

# dark
# light
# user-can-set
appearance: auto # Default value is auto

# Miscellaneous
favicon: images/favicon.jpg

friend_links:
  # - title: V2EX
  #   link: https://v2ex.com/
  # - title: Twitter
  #   link: https://twitter.com/

# Google Analytics
ga_track_id:
ga_domain:

# Baidu Analytics
ba_track_id:

# picture of about page
about_pic: about.jpg

image_zoom:
  enable: true